id: P66974443
initial_creation_type: input
source_metadata:
  Title: Bhavasaṅkrāntisūtram
  Editor: Shastri, N..Aiyaswami
  Publisher: The Adyar Library
  Place of Publication: Madras
  Year: '1938'
  Bhavasaṅakrāntisūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:00:24.774215'
last_modified_at: '2022-03-08T16:00:24.774225'
